# Generated by Django 2.1.7 on 2019-03-14 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='athlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_calendar', to='training_area.Athlete'),
        ),
        migrations.AddField(
            model_name='event',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_calendar', to='training_area.Coach'),
        ),
    ]
