# Generated by Django 2.1.7 on 2019-03-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0005_auto_20190314_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
