# Generated by Django 2.1.7 on 2019-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0007_auto_20190318_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
    ]
