# Generated by Django 2.1.7 on 2019-03-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0008_auto_20190318_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repmax',
            name='rep_max',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='1-RM'),
        ),
    ]
