# Generated by Django 2.1.7 on 2019-04-04 08:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0009_auto_20190321_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='fatigue_rating',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Fatigue Rating'),
        ),
        migrations.AlterField(
            model_name='microcycle',
            name='mesocycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meso', to='training_area.Mesocycle'),
        ),
    ]
