# Generated by Django 2.1.7 on 2019-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0010_auto_20190404_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='mesocycle_name',
            field=models.CharField(max_length=255, verbose_name='Block Name'),
        ),
    ]
