# Generated by Django 2.1.7 on 2019-04-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0012_auto_20190409_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='units',
            field=models.IntegerField(choices=[(0, 'metres'), (1, 'seconds'), (2, 'minutes'), (3, 'reps')], default=3),
        ),
    ]
