# Generated by Django 2.1.7 on 2019-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0013_accessory_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='measurement_done',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='measurement',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
