# Generated by Django 2.1.7 on 2019-04-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_area', '0014_auto_20190409_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='measurement',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
